Feature/copy users and rights
openstad/openstad-management-panel pull request #68
Opened 2022-09-13 07:39 UTC by LorenzoJokhan

# Description
On the Admin panel, when you either create, copy or import sites, you will have the option to import users from a selected site to the new site. This will happen after the site has been created.

## Issue reference

Fixes # (issue)
https://trello.com/c/W4LNEp4J

## Type of change
feature

## Tests
For the copy site functionality
- Log in to admin panel
- Create a website with the create site functionality with a few users and roles of your choosing (and log in with the users on that specific site)
- Use the copy site function to create a website based of the previously created site
- Check the checkbox that enables the copying of users and rights

The create and import pages work in the same manner with the exception that you will need to check the checkbox and search for a specific site in the combobox.

2022-09-13 07:54 UTC, Badmuts approved these changes
LGTM 👍

2022-09-13 09:18 UTC, nlsvgtr requested changes

2022-09-13 09:18 UTC, nlsvgtr commented on services/siteApi.js
> +  return rp({
Be aware that request-promise is deprecated and should be migrated to node-fetch. This has apparently already been done in `providers/oauthProvider.js` above.

You might want to consider to migrate this file while your at it.

2022-09-13 09:18 UTC, nlsvgtr commented on providers/oauthProvider.js
> +  return fetch(
I don't have a problem with direct api calls, but it would be more consistent to use 
the userService as with all other requests done here.

2022-09-13 09:18 UTC, nlsvgtr commented on providers/oauthProvider.js
> +  const usersOfOldSite = await siteApi.fetchUsersOfSite(oldSiteId);
Since users (actually: userroles) are copied to the oauth server they should be fetched from the oauth server, not from the API.

2022-09-13 09:18 UTC, nlsvgtr commented on providers/oauthProvider.js
> +  const usersOfOldSite = await siteApi.fetchUsersOfSite(oldSiteId);
Furthermore you should copy much less than is done now:
1. it is not necessary to copy users with the default role; that is automatically added when a user tries to login
2. anonymous users should probably not be copied

2022-09-15 09:51 UTC, nlsvgtr approved these changes
Very nice. Thanks

2022-09-15 10:12 UTC, merged